version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    working_dir: /app
    env_file:
      - src/.env
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "8000:8000"

  db:
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dbname
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
