"""init

Revision ID: a81c6f2ad53f
Revises: 
Create Date: 2023-06-23 22:58:23.042809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a81c6f2ad53f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "house",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cadastral_number", sa.String(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cadastral_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("house")
    # ### end Alembic commands ###
