"""add_calculate_field

Revision ID: c08934c4db87
Revises: a81c6f2ad53f
Create Date: 2023-06-24 01:36:36.409087

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c08934c4db87"
down_revision = "a81c6f2ad53f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "house", sa.Column("calculated", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("house", "calculated")
    # ### end Alembic commands ###
